spring.application.name=billingApp
spring.datasource.url: jdbc:postgresql://retail-billing-db-server.postgres.database.azure.com:5432/billing_app?sslmode=require

# Find this FQDN in the 'Overview' tab of your Azure server
spring.datasource.username: dbadmin
spring.datasource.password: Indian1!
spring.jpa.hibernate.ddl-auto: update

# Use 'update' so Hibernate creates the tables for your store automatically
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

# Increase the pool size (4 is very low for a web app)
spring.datasource.hikari.maximum-pool-size=10

# How long a thread will wait for a connection before failing (30 seconds)
spring.datasource.hikari.connection-timeout=30000

# How long a connection can sit idle before being retired
spring.datasource.hikari.idle-timeout=600000

# Force-close connections that have been out too long (Leak Detection)
spring.datasource.hikari.leak-detection-threshold=2000

# Customizing Swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html
# Sorting endpoints alphabetically
springdoc.swagger-ui.operationsSorter=alpha