-- Required BEFORE starting an installation using ddl-auto=validate.
-- Local/QA/desktop ddl-auto=update creates the tables/columns automatically.
-- StockMovementSchemaUpgrade expands the legacy PostgreSQL enum check in update mode.
-- Apply 20261008-stock-movements.sql first if that table does not exist yet.
BEGIN;
ALTER TABLE purchase_bills ADD COLUMN IF NOT EXISTS returned_amount double precision DEFAULT 0;
ALTER TABLE purchase_bills ADD COLUMN IF NOT EXISTS refunded_amount double precision DEFAULT 0;
ALTER TABLE purchase_bill_items ADD COLUMN IF NOT EXISTS returned_quantity double precision DEFAULT 0;
ALTER TABLE purchase_payments ADD COLUMN IF NOT EXISTS refund boolean DEFAULT false;
ALTER TABLE purchase_payments ADD COLUMN IF NOT EXISTS request_key varchar(36);
ALTER TABLE purchase_payments ADD COLUMN IF NOT EXISTS fingerprint varchar(64);
ALTER TABLE purchase_payments ADD COLUMN IF NOT EXISTS actor_name varchar(160);
CREATE UNIQUE INDEX IF NOT EXISTS uk_purchase_payment_request ON purchase_payments(purchase_bill_id, request_key);

CREATE TABLE IF NOT EXISTS purchase_returns (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_bill_id bigint NOT NULL REFERENCES purchase_bills(id),
    request_key varchar(36) NOT NULL,
    fingerprint varchar(64) NOT NULL,
    reason varchar(500) NOT NULL,
    credit_amount double precision NOT NULL,
    actor_name varchar(160) NOT NULL,
    actor_user_id varchar(160),
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uk_purchase_return_request UNIQUE (purchase_bill_id, request_key)
);
CREATE TABLE IF NOT EXISTS purchase_return_items (
    purchase_return_id bigint NOT NULL REFERENCES purchase_returns(id),
    line_index integer NOT NULL,
    purchase_item_id bigint NOT NULL,
    product_id bigint NOT NULL,
    product_name varchar(255),
    quantity double precision NOT NULL,
    credit_amount double precision NOT NULL,
    PRIMARY KEY (purchase_return_id, line_index)
);

-- Replace only the old enum-style, single-column check; preserve unrelated constraints.
DO $$ DECLARE old_check record; BEGIN
  FOR old_check IN
    SELECT c.conname FROM pg_constraint c
    JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = c.conkey[1]
    WHERE c.conrelid = 'stock_movements'::regclass AND c.contype = 'c'
      AND cardinality(c.conkey) = 1 AND a.attname = 'type'
      AND pg_get_constraintdef(c.oid) LIKE '%OPENING_STOCK%'
      AND pg_get_constraintdef(c.oid) LIKE '%SALE_CANCELLED%'
      AND pg_get_constraintdef(c.oid) NOT LIKE '%PURCHASE_RETURN%'
  LOOP
    EXECUTE format('ALTER TABLE stock_movements DROP CONSTRAINT %I', old_check.conname);
    EXECUTE format('ALTER TABLE stock_movements ADD CONSTRAINT %I CHECK (type IN
      (''BALANCE_BROUGHT_FORWARD'',''OPENING_STOCK'',''ADJUSTMENT'',''PURCHASE'',
       ''PURCHASE_RETURN'',''PURCHASE_CANCELLED'',''SALE'',''SALE_RETURN'',''SALE_CANCELLED''))', old_check.conname);
  END LOOP;
END $$;
COMMIT;
