-- For installations using spring.jpa.hibernate.ddl-auto=validate.
-- Local/QA/desktop installations create this table automatically with ddl-auto=update.
BEGIN;
CREATE TABLE IF NOT EXISTS stock_movements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id varchar(255) NOT NULL,
    product_id bigint NOT NULL,
    product_name varchar(255),
    barcode varchar(64),
    type varchar(40) NOT NULL,
    reason varchar(80) NOT NULL,
    notes varchar(500),
    quantity_before double precision NOT NULL,
    quantity_change double precision NOT NULL,
    quantity_after double precision NOT NULL,
    reference varchar(240),
    source_name varchar(240),
    reference_id bigint,
    actor_user_id varchar(160),
    actor_name varchar(160) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_stock_movements_tenant_product ON stock_movements (tenant_id, product_id, id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_tenant_date ON stock_movements (tenant_id, created_at, id);
COMMIT;
