-- Required BEFORE starting a production installation with ddl-auto=validate.
-- Local/QA/desktop ddl-auto=update creates these tables and columns on restart.
BEGIN;
CREATE TABLE IF NOT EXISTS cashier_shifts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id varchar(255) NOT NULL,
    cashier_user_id varchar(255) NOT NULL,
    cashier_name varchar(160) NOT NULL,
    counter_name varchar(120),
    active_marker integer,
    open_request_key varchar(36) NOT NULL,
    open_fingerprint varchar(64) NOT NULL,
    close_request_key varchar(36),
    close_fingerprint varchar(64),
    opened_at timestamp(6) without time zone NOT NULL,
    closed_at timestamp(6) without time zone,
    closed_by_user_id varchar(255),
    closed_by_name varchar(160),
    close_notes varchar(1000),
    opening_cash numeric(19,2) NOT NULL,
    expected_cash numeric(19,2),
    counted_cash numeric(19,2),
    variance numeric(19,2),
    cash_received numeric(19,2),
    cash_refunded numeric(19,2),
    upi_received numeric(19,2),
    upi_refunded numeric(19,2),
    card_received numeric(19,2),
    card_refunded numeric(19,2),
    manual_cash_in numeric(19,2),
    manual_cash_out numeric(19,2),
    CONSTRAINT uk_shift_active_cashier UNIQUE(tenant_id, cashier_user_id, active_marker),
    CONSTRAINT uk_shift_open_request UNIQUE(tenant_id, cashier_user_id, open_request_key)
);
CREATE INDEX IF NOT EXISTS idx_shifts_tenant_opened ON cashier_shifts(tenant_id, opened_at, id);
CREATE TABLE IF NOT EXISTS shift_cash_movements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id varchar(255) NOT NULL,
    shift_id bigint NOT NULL REFERENCES cashier_shifts(id),
    request_key varchar(36) NOT NULL,
    fingerprint varchar(64) NOT NULL,
    cash_in boolean NOT NULL,
    amount numeric(19,2) NOT NULL,
    reason varchar(500) NOT NULL,
    reference varchar(240),
    actor_user_id varchar(255) NOT NULL,
    actor_name varchar(160) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uk_shift_cash_request UNIQUE(shift_id, request_key)
);
CREATE INDEX IF NOT EXISTS idx_shift_cash_movement ON shift_cash_movements(tenant_id, shift_id, id);
ALTER TABLE bills ADD COLUMN IF NOT EXISTS cashier_user_id varchar(255);
ALTER TABLE bills ADD COLUMN IF NOT EXISTS shift_id bigint;
ALTER TABLE bill_payments ADD COLUMN IF NOT EXISTS cashier_user_id varchar(255);
ALTER TABLE bill_payments ADD COLUMN IF NOT EXISTS shift_id bigint;
CREATE INDEX IF NOT EXISTS idx_bill_payments_shift ON bill_payments(shift_id, id);
COMMIT;
