-- Apply after the existing inventory, shift and GST migrations, before using ddl-auto=validate.
-- Existing stores are registered as LEGACY by LicenseBootstrap on first start; no transactions are changed.
BEGIN;
ALTER TABLE users ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT true;
ALTER TABLE cashier_shifts ADD COLUMN IF NOT EXISTS license_counter_id varchar(36);
CREATE UNIQUE INDEX IF NOT EXISTS uk_shift_active_counter ON cashier_shifts(tenant_id, license_counter_id, active_marker);
CREATE TABLE IF NOT EXISTS license_installation (
    id integer PRIMARY KEY,
    deployment_id varchar(36) NOT NULL
);
CREATE TABLE IF NOT EXISTS tenant_licenses (
    tenant_id varchar(100) PRIMARY KEY,
    deployment_id varchar(36) NOT NULL,
    legacy_access boolean NOT NULL,
    legacy_migrated boolean NOT NULL DEFAULT false,
    signed_license text,
    signed_history text,
    accepted_license_id varchar(100),
    accepted_revision bigint NOT NULL DEFAULT 0,
    version bigint NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS licensed_counters (
    id varchar(36) PRIMARY KEY,
    tenant_id varchar(100) NOT NULL,
    name varchar(120) NOT NULL,
    active boolean NOT NULL,
    UNIQUE(tenant_id, name)
);
CREATE INDEX IF NOT EXISTS idx_license_counters_tenant ON licensed_counters(tenant_id);
CREATE TABLE IF NOT EXISTS license_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id varchar(100) NOT NULL,
    action varchar(255) NOT NULL,
    details varchar(1000) NOT NULL,
    actor varchar(255),
    created_at timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_license_audit_tenant ON license_audit(tenant_id, id);
COMMIT;
